[package]
name = "geocoder-abbreviations"
version = "0.1.0"
authors = ["Mapbox <info@mapbox.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.3.0"
regex = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_regex = "0.3"
